### ISSUE TITLE
Is it still in development?

### ISSUE THREAD

**Issue by marilotte** [radeklat/todoist-habitica-sync#1]
Hello,
I really love the idea of this project and the nicely reduced functionality. And I just wanted to ask: are you still working on it? I‘m really interested in using it and would love to help. However, I‘m not firm in Python. 

Best, Amber

**Comment by radeklat** [comment]
Hi Amber. Not at the moment as I stopped using Habitica. But I could pick it up again as a fun side project if there will be more people interested. Can you please tell me more on where would you be able to run it? I used to run it in a screen on my VPS but I could wrap it into a docker container for example.

**Comment by marilotte** [comment]
Thanks for getting back so fast :)
I use Mac BigSur at the moment and thought I could run it "as is" and maybe wrap it in a time sensitive function. However, if it would useful to you, I have the possibility to test it on several machines.

**Comment by radeklat** [comment]
I haven't tested it on macOS but I can (I don't expect any problems). And you could definitely run it like that. It already has a configurable delay built in so you could just run it as it is. So I supposed at the moment, it is missing a user guide for macOS and testing if it still works. I'm happy to do both. Knowledge of brew and pip should be more than enough :+1:

**Comment by marilotte** [comment]
That would be really great! Thank you so much.

**Comment by radeklat** [comment]
I updated the [installation instructions](https://github.com/radeklat/todoist-habitica-sync#as-a-script) for running locally. Let me know if you manage to run it or run into any issues.

**Comment by marilotte** [comment]
Hallo,
I found some time to test it and it works like a charm, thank you so much! 

If some other unexperience mac users see this: If you have problems installing some of the depencencies, try updating Xcode: xcode-select --install
This should do the trick :)

**Comment by radeklat** [comment]
@marilotte I could add it to the installation guide. Do you remember what exactly was the problematic dependency?
