### ISSUE TITLE
Assigned task to another user is counted in habitica

### ISSUE THREAD

**Issue by mevaere** [radeklat/todoist-habitica-sync#17]
If I assigned a task to my collaborator and it checked this task then it will be added and finished on my habitica. This is a bug cause I get rewards when my collaborators works ;)

`def _should_task_score_points(todoist_task: TodoistTask, generic_task: GenericTask = None) -> bool:`

Maybe should be used "responsible_uid" in the Items API of todoist ?

**Comment by radeklat** [comment]
Hi Rémi. That sounds reasonable. I didn't take collaborative environment into account. I will fix that :+1:

**Comment by mevaere** [comment]
I tried to fix the bug. It's just an idea and my first pull request.  Have a nice day

**Comment by radeklat** [comment]
Implemented in [2.1.0](https://github.com/radeklat/todoist-habitica-sync/blob/main/CHANGELOG.md#210---2022-03-06). Thank you for your suggestion :pray:
