### ISSUE TITLE
Error when running "poetry run python src/main.py"

### ISSUE THREAD

**Issue by gkronisch** [radeklat/todoist-habitica-sync#35]
Command ['python', '-I', '-W', 'ignore', '-'] errored with the following return code 2

Error output:
Unknown option: -I
usage: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

Input:
import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)

**Comment by radeklat** [comment]
Hi there. Thank you for you report. This looksl ike an error coming from the system rather than `todoist-habitica-sync`. I didn't manage to reproduce it with the latest version of poetry. Please check that you have the latest version of poetry with `poetry --version`. The latest is `1.4.2`. You can update it with `pip install -U poetry`.

If this doesn't help, please consider [running `todoist-habitica-sync` via docker compose](https://github.com/radeklat/todoist-habitica-sync#as-a-service), which will abstract you local environment away and remove many variables that can cause errors.

**Comment by gkronisch** [comment]
I think this worked! Thank you so much!
I don't have much experience in running scripts so it's been hard to figure some of this stuff out. I really appreciate your help.
I will let you know if there are any other errors.

**Comment by gkronisch** [comment]
Please see the attached terminal screenshot. I used your Docker compose suggestion, and it seems to be working well from Docker's / terminal's side. 

<img width="697" alt="Screen Shot 2023-04-05 at 11 59 11 PM" src="https://user-images.githubusercontent.com/40045948/230122020-d7753f83-99bc-422c-be98-c6a3989e8230.png">

However, there was no change in my Habitica screen, or rewards of any kind. I could not see the task under Completed to-dos in Habitica.

I tried to initially use this program with a script, and at that time I did not enter my Habitica User ID in the .env file. Maybe that's what's causing the issue? I'm not sure.

**Comment by gkronisch** [comment]
Update: it works when running the normal docker compose up
but does not seem to work when running docker compose up --detach (to run in background)...

**Comment by radeklat** [comment]
Note that the program will not award anything for tasks completed in the past. It will only award future completions. There should be no difference between using `--detach` or not. If you use `docker compose up --detach`, you can still view the logs later with `docker compose logs --tail 100 -f`.

Please try running it in the background with:

```
docker compose up --detach
```

Then start watching the logs with:

```
docker compose logs --tail 100 -f
```

Then try to complete a task in Todoist.

After the wait period, you should see the completed task is picked up and synchronised into Habitica.
