### ISSUE TITLE
Recurring Tasks not logged after 1st completion

### ISSUE THREAD

**Issue by qfettes** [radeklat/todoist-habitica-sync#4]
My recurring tasks with 'every' in the date string are not logged in habitica after the first completion in todoist.

I saw that you mentioned you are no longer maintaining this code; if you could point me to the section of the code that should handle this logic, I could try fixing it myself.

**Comment by radeklat** [comment]
Hi @qfettes. Thanks for both of your reports. I'm not actively developing this tool as I no longer use it myself. But I do maintain it if issues are reported. I will have a look at both this one and #3. You are of course always welcome to fork this repository and make a pull request.

**Comment by radeklat** [comment]
Fixed in [`2.0.0`](https://github.com/radeklat/todoist-habitica-sync/blob/main/CHANGELOG.md#200---2022-01-30). Please [reset the sync cache](https://github.com/radeklat/todoist-habitica-sync#resetting-sync-cache) before starting the app after the update.
