### ISSUE TITLE
unable to install poetry project

### ISSUE THREAD

**Issue by junefish** [radeklat/todoist-habitica-sync#44]
Previous versions of this repo worked for me, but I just tried to set it up on a new computer (MacOS) and am running into the following when I try to run `poetry install --no-dev`:
```
$ poetry install --no-dev 
The virtual environment found in /Users/junefish/Github/todoist-habitica-sync/.venv seems to be broken.
Recreating virtualenv todoist-habitica-sync in /Users/junefish/Github/todoist-habitica-sync/.venv
The `--no-dev` option is deprecated, use the `--only main` notation instead.
Installing dependencies from lock file

Package operations: 16 installs, 0 updates, 0 removals

  • Installing typing-extensions (4.8.0)
  • Installing annotated-types (0.6.0)
  • Installing pydantic-core (2.10.1)
  • Installing certifi (2023.7.22)
  • Installing charset-normalizer (3.3.2)
  • Installing idna (3.4)
  • Installing pydantic (2.4.2)
  • Installing python-dotenv (1.0.0)
  • Installing six (1.16.0)
  • Installing urllib3 (2.0.7)
  • Installing dotmap (1.3.30)
  • Installing pydantic-settings (2.0.3)
  • Installing python-dateutil (2.8.2)
  • Installing requests (2.31.0)
  • Installing tinydb (4.8.0)
  • Installing ujson (5.8.0)

Installing the current project: todoist-habitica-sync (3.0.1)
The current project could not be installed: No file/folder found for package todoist-habitica-sync
If you do not want to install the current project use --no-root
```

Here are the software versions I'm using:
- git version 2.39.3 (Apple Git-145)
- Python 3.12.0
- Poetry (version 1.7.1)

Please let me know if any other info would be helpful.

**Comment by radeklat** [comment]
Hey @junefish. Thank you for letting me know. It seem that one of the newer versions of Poetry introduced a requirement which makes the current installation instructions not to work any more. I updated the instructions in #45. The new way of installing / updating the dependencies is `poetry install --no-root --without=dev`. The missing `--no-root` flag was causing the problem. Additionally, `--no-dev` has been deprecated and the new way of specifying the same is `--without=dev`.
