### ISSUE TITLE
[Errno 2] No such file or directory: 'python'

### ISSUE THREAD

**Issue by twoesplease** [radeklat/todoist-habitica-sync#46]
When attempting to run 
`poetry install --no-root --without=dev`

I receive the error message:
`[Errno 2] No such file or directory: 'python'`

I have updated & sourced my .zshrc to alias `python` to `python3` but am not sure which file to update to do the same.

Steps I have taken:
- cloned repo
- installed poetry via `brew`
- added APIkey & userID details to `.env`

So I am on step #8 to install the deps via the `poetry install --no-root --without=dev` command.  Rather than change every instance of `python` to `python3` throughout the codebase, I figured I'd just ask since I haven't used poetry before.

Thanks!

Edited to add:
```
$ python3 --version
> Python 3.12.0
```
```
$poetry --version
> Poetry (version 1.7.1)
```

**Comment by twoesplease** [comment]
NVM, I got it!  Had to update my zshrc to update my PATH.

**Comment by radeklat** [comment]
I'm glad @twoesplease you managed to make it work for you in the end! Thank you for the link back to the instructions how to fix. It may help someone else with a the same problem in the future.

Just a side note, you can avoid problems with setting up an environment locally by using [docker containers instead](https://github.com/radeklat/todoist-habitica-sync#as-a-docker-container) (as they contain all the environment already).

**Comment by stacksjb** [comment]
I ran into this same error. Homebrew does not support remapping or linking anymore (and they [ask that you don't](https://justinmayer.com/posts/homebrew-python-is-not-for-you/))

However, I was able to get it to work by [symlinking](https://apple.stackexchange.com/questions/454573/how-can-i-set-python-symlink-in-macos-ventura) to the latest python (either manually installed from python.org)

```
sudo ln -sf /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 /usr/local/bin/python
```
(replace with the path to your currently installed python)
