### ISSUE TITLE
Create Habbtitica Task when created in Todoist

### ISSUE THREAD

**Issue by RandomUser123467** [radeklat/todoist-habitica-sync#48]
Hey! I love your project! However, I want it to create a task in Habitica when it does in Todoist. The rest of the functions are fine. I want to be able to view my tasks in both Habitica and Todoist. Is it possible for you to do this? I have no programming knowledge.

**Comment by radeklat** [comment]
Hey :wave: Thank you for the suggestion. It would be possible to do, but that is not the point of this tool. My intention is to use tasks only in one place, not two. So I'm not going to add this. However, there are other tools that seem to be doing the kind of sync you are after: https://habitica.fandom.com/wiki/Habitica-Todo
