### ISSUE TITLE
Continuously Running Script

### ISSUE THREAD

**Issue by RandomUser123467** [radeklat/todoist-habitica-sync#50]
Hi it's me again,

Do I have to constantly run the script in the background for it to update? Or is there a manual command I can run?

**Comment by RandomUser123467** [comment]
Also where is the .env file? All I can see is env.template and env.test

**Comment by radeklat** [comment]
Hi @RandomUser123467.

> Do I have to constantly run the script in the background for it to update? Or is there a manual command I can run?

At the moment, it runs in a loop and waits between updates. Both the Todoist API and the Habitica API have limits, so the update takes a few seconds to minutes, depending on the number of completed tasks.

> Also where is the .env file? All I can see is env.template and env.test

You need to create it by copying the `.env.template` into `.env` and filling in your details. This is documented in step 6 of [Running as a script](https://github.com/radeklat/todoist-habitica-sync?tab=readme-ov-file#as-a-script) and step 3 of [Running a docker container](https://github.com/radeklat/todoist-habitica-sync?tab=readme-ov-file#as-a-docker-container) / [as a service](https://github.com/radeklat/todoist-habitica-sync?tab=readme-ov-file#as-a-service).

**Comment by RandomUser123467** [comment]
So I have to keep it running on my computer?
________________________________

**Comment by radeklat** [comment]
Either on your computer or if you have access to a server, Raspberry PI etc. that is already running continuously, it can run there as well. If you have just your computer, I recommend the [Running as a service](https://github.com/radeklat/todoist-habitica-sync#as-a-service) option. It will run automatically in the background, even if you restart your computer.

**Comment by RandomUser123467** [comment]
Ok, I don't have a server that's running constantly, is there any way I can do this for free?
Also thanks for answering all my questions! Sorry if I'm spamming you.
________________________________

**Comment by radeklat** [comment]
I don't know about any free server option at the moment. So the only completely free option is running it on your computer.

**Comment by RandomUser123467** [comment]
Ok! Thanks.
________________________________

**Comment by radeklat** [comment]
No worries :)
