### ISSUE TITLE
New feature "Use @ Todoist labels for difficulty"

### ISSUE THREAD

**Issue by danbo-ark** [radeklat/todoist-habitica-sync#56]
Hey Radeklat,

I love Habitica and your Todoist tool. Are you still developing it? The function "Use @ Todoist labels for difficulty" would be awesome ... I don't get on so well with p1 p2 p3 p4.

Best regards
Danbo

**Comment by radeklat** [comment]
Hello @danbo-ark. I'm not using Habitca actively at the moment and this tool is now more in a maintenance mode. But I still consider it active.

I added the requested feature in 3.4.0. You need to define which Todoist labels map to which Habitica difficulties with [`LABEL_TO_DIFFICULTY`](https://github.com/radeklat/todoist-habitica-sync?tab=readme-ov-file#label_to_difficulty).
